version: "3.9"

services:
  flavor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flavor_app
    ports:
      - "8501:8501"   # expose on EC2 public IP
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
    restart: always
